version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: tbx-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - tbx-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tbx-frontend
    ports:
      - "8080:8080"
    environment:
      - API_URL=http://api:3000
    depends_on:
      - api
    networks:
      - tbx-network

networks:
  tbx-network:
    driver: bridge